---

- name: Set the hostname
  hostname: name={{ inventory_hostname }}

- name: Update the hostname (/etc/hosts)
  lineinfile: dest=/etc/hosts
    regexp="^127\.0\.1\.1\s+{{ fqdn }}\s+{{ inventory_hostname }}"
    line="127.0.1.1  {{ fqdn }}  {{ inventory_hostname }}"
    state=present

- name: Set the locale
  template: src=locale.j2 dest=/etc/default/locale owner=root group=root

- name: Set the timezone
  file: src=/usr/share/zoneinfo/{{ timezone }}
        dest=/etc/localtime
        force=yes
        state=link
  tags: timezone
