---

- name: update hostname
  command: /usr/bin/hostnamectl set-hostname {{ inventory_hostname }}

- name: update timezone
  command: /usr/bin/timedatectl set-timezone {{ timezone }}

- name: generate locales
  command: /usr/bin/locale-gen

- name: restart journald
  service: name=systemd-journald state=restarted

- name: restart logind
  service: name=systemd-logind state=restarted

- name: reload systemd daemon
  command: /usr/bin/systemctl daemon-reload
