---

# Stop regular sshd.service before enabling socket
- name: enable ssh socket
  service: name=sshd.service state=stopped enabled=no
  notify: restart ssh socket

- name: restart ssh socket
  service: name=sshd.socket state=restarted enabled=yes
