---

- name: set hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root
  notify: update hostname

- name: Update the hostname (/etc/hosts)
  lineinfile: dest=/etc/hosts
    regexp="^{{ansible_default_ipv4.address}}\s+{{ fqdn }}\s+{{ inventory_hostname }}"
    line="{{ansible_default_ipv4.address}}  {{ fqdn }}  {{ inventory_hostname }}"
    state=present

- name: set timezone
  template: src=timezone.j2 dest=/etc/timezone owner=root group=root
  notify: update timezone

- name: set available locales
  template: src=locale.gen.j2 dest=/etc/locale.gen owner=root group=root
  notify: generate locales

- name: set default locale
  template: src=locale.j2 dest=/etc/locale.conf owner=root group=root

- name: set vconsole keymap
  lineinfile: dest=/etc/vconsole.conf create=yes
      regexp="^KEYMAP=" line="KEYMAP={{ systemd_vconsole_keymap }}"

- name: set vconsole font
  lineinfile: dest=/etc/vconsole.conf
      regexp="^FONT=" line="FONT={{ systemd_vconsole_font }}"

- name: persist journal
  file: path=/var/log/journal state=directory

- name: configure journald
  template: src=journald.conf.j2 dest=/etc/systemd/journald.conf owner=root group=root
  notify: restart journald

- name: configure logind
  template: src=logind.conf.j2 dest=/etc/systemd/logind.conf owner=root group=root
  notify: restart logind

- name: Archlinux | SSHd socket port
  template:
    src=port.conf owner=root group=root
    dest=/etc/systemd/system/sshd.socket.d/port.conf
  notify: reload systemd daemon
  tags: ssh
