---

- name: skel - Get /etc/skel from github.com/rafi
  git: depth=1 dest=/tmp/etc-skel repo=git://github.com/rafi/etc-skel.git
       force=no accept_hostkey=yes
  tags: skel

- name: skel - Copy skel to /etc/skel
  command: rsync -rl --exclude=.git /tmp/etc-skel/ /etc/skel/
           creates=/etc/skel/.config/bash/bashrc
  tags: skel

- name: skel - Ensure .bash_profile is absent
  file: path=/etc/skel/.bash_profile state=absent
  tags: skel
